language: node_js
compiler:
  - gcc
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Node 0.8 comes with a too obsolete npm
  - if [[ "`node --version`" =~ ^v0\.8\. ]]; then npm install -g npm@1.4.28 ; fi
  # Install dependencies and build
  - npm install
